### ISSUE TITLE
Output raw

### ISSUE THREAD

**Issue by gyroing** [wide-video/piper-wasm#1]
Hi 
I wonder is it any solution to  stdout audiobuffer as stream with --output_raw option and handle it with javascript Dom?

**Comment by jozefchutka** [comment]
Hi, [emscripten](https://emscripten.org/docs/api_reference/module.html) (piper-wasm) does support both stdin and stdout and there is support for stdout in [piper](https://github.com/rhasspy/piper?tab=readme-ov-file#streaming-audio). 
On javascript side one could use [decodeAudioData](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData) to play these bytes... Considering all these technologies support it, I believe it should be doable.
